OPCodes = {

                "=" :               0,
                "+" :               1,
                "-" :               2,
                "*" :               3,
                "/" :               4,
                "==" :              5,
                ">" :               6,
                "<" :               7,
                ">=" :              8,
                "<=" :              9,
                "&&" :              10,
                "||" :              11,
                "!=" :              12,
                "!" :               13,
                "ARR_ACCESS" :      14,
                "ARR_BNDS" :        15,
                "TMP_RESET":        16,
                "OBJ_INST" :        17,
                "OBJ_READ" :        18,
                "OBJ_WRITE" :       19,
                "ERA" :             20,
                "PARAM" :           21,
                "GOSUB" :           22,
                "OBJ_GOSUB" :       23,
                "READ" :            24,
                "PRNTBFFR" :        25,
                "PRNT" :            26,
                "PRNTLN" :          27,
                "GOTO" :            28,
                "GOTOF" :           29,
                "ENDFNC" :          30,
                "END" :             31,


}
