OPCodes = {

                "=" :               0,
                "+" :               1,
                "-" :               2,
                "*" :               3,
                "/" :               4,
                "==" :              5,
                ">" :               6,
                "<" :               7,
                ">=" :              8,
                "<=" :              9,
                "&&" :              10,
                "||" :              11,
                "!=" :              12,
                "!" :               13,
                "ARR_ACCESS" :      14,
                "ARR_BNDS" :        15,
                "TMP_RESET":        16,
                "USNG_AS" :         17,
                "OBJ_INST" :        18,
                "OBJ_READ" :        19,
                "OBJ_WRITE" :       20,
                "ERA" :             21,
                "PARAM" :           22,
                "GOSUB" :           23,
                "OBJ_GOSUB" :       24,
                "READ" :            25,
                "PRNTBFFR" :        26,
                "PRNT" :            27,
                "PRNTLN" :          28,
                "STOX"  :           29,
                "SUBSTR" :          30,
                "F_OPEN" :          31,
                "F_WRITE" :         32,
                "GOTO" :            33,
                "GOTOF" :           34,
                "ENDFNC" :          35,
                "END" :             36,


}
